export const PostActionTypes = {
  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAIL: "ADD_POST_FAIL",

  UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAIL: "UPDATE_POST_FAIL",

  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAIL: "DELETE_POST_FAIL",

  GET_POST_REQUEST: "GET_POST_REQUEST",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAIL: "GET_POST_FAIL",

  GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAIL: "GET_POSTS_FAIL",

  GET_POSTS_BY_CATEGORY_REQUEST: "GET_POSTS_BY_CATEGORY_REQUEST",
  GET_POSTS_BY_CATEGORY_SUCCESS: "GET_POSTS_BY_CATEGORY_SUCCESS",
  GET_POSTS_BY_CATEGORY_FAIL: "GET_POSTS_BY_CATEGORY_FAIL",
};
